import { MD3LightTheme as DefaultTheme } from 'react-native-paper';

export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#2e7d32',
    onPrimary: '#ffffff',
    primaryContainer: '#a5d6a7',
    onPrimaryContainer: '#1b5e20',
    secondary: '#4caf50',
    onSecondary: '#ffffff',
    secondaryContainer: '#c8e6c9',
    onSecondaryContainer: '#2e7d32',
    tertiary: '#66bb6a',
    onTertiary: '#ffffff',
    tertiaryContainer: '#e8f5e8',
    onTertiaryContainer: '#1b5e20',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#410002',
    background: '#f5f5f5',
    onBackground: '#1a1c18',
    surface: '#ffffff',
    onSurface: '#1a1c18',
    surfaceVariant: '#e0e0e0',
    onSurfaceVariant: '#424242',
    outline: '#757575',
    outlineVariant: '#bdbdbd',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2f312d',
    inverseOnSurface: '#f1f1eb',
    inversePrimary: '#81c784',
    elevation: {
      level0: 'transparent',
      level1: '#f8f8f8',
      level2: '#f3f3f3',
      level3: '#eeeeee',
      level4: '#ebebeb',
      level5: '#e8e8e8',
    },
    surfaceDisabled: '#e0e0e0',
    onSurfaceDisabled: '#9e9e9e',
    backdrop: 'rgba(0, 0, 0, 0.4)',
  },
};
